from typing import Optional, Union, Type, Dict
from gameboy_worlds.emulation.parser import StateParser
from gameboy_worlds.emulation.tracker import StateTracker
from gameboy_worlds.emulation.emulator import Emulator
from gameboy_worlds.emulation.harry_potter.parsers import (
    HarryPotterPhilosophersStoneParser,
    HarryPotterChamberOfSecretsParser,
)
from gameboy_worlds.emulation.harry_potter.trackers import (
    ReceiveFolioMagiTestTracker,
    SelectCardDeckTestTracker,
    TalkHagridGringottsTestTracker,
    ExitGringottsWithoutHagridTestTracker,
    GetOnTrainTestTracker,
    BuyChocolateFrogsTestTracker,
    SellOneChocolateFrogTestTracker,
    LoseDuelTestTracker,
    WinDuelTestTracker,
    GainLevelTestTracker,
    GainSpellTestTracker,
    WinBattleTestTracker,
    BeatBossRatTestTracker,
    FailRatKingBattleTestTracker,
    DefeatRatKingWithDeflectTestTracker,
    HarryPotterOCRTracker,
    FindHagridVaultTestTracker,
    EnterMalkinsTestTracker,
    OpenMalkinsBuyMenuTestTracker,
    SelectRobesTestTracker,
    ConfirmRobesPurchaseTestTracker,
    EnterFlourishBlottsTestTracker,
    BuyBooksTestTracker,
    EnterApothecaryTestTracker,
    BuyPotionKitTestTracker,
    EnterCauldronShopTestTracker,
    BuyCauldronTestTracker,
    EnterSugarplumsTestTracker,
    OpenSugarplumsBuyMenuTestTracker,
    WalkTrain3TimesTestTracker,
    TalkToHagridDiagonTestTracker,
    FindDobbyTestTracker,
    SelectCardDeckCosTestTracker,
    BoardFlyingCarTestTracker,
    EnterBurrowTestTracker,
    EnterBattleCosTestTracker,
    EnterPercyRoomTestTracker,
    EnterGinnyRoomTestTracker,
    EnterParentsRoomTestTracker,
    EnterFredGeorgeRoomTestTracker,
    EnterRonsRoomTestTracker,
    TalkToRonBurrowTestTracker,
    EnterKitchenBurrowTestTracker,
    EnterBurrowGardenTestTracker,
    NavigateToCarTestTracker,
    StartMenuTestTracker,
    EatPumpkinPastyTestTracker,
    EquipPointedHatPlainWorkRobeTestTracker,
    RemoveAllEquippedItemsTestTracker,
    TalkToHagridBoatTestTracker,
    DieTestTracker,
    FightRatThenMonsterTestTracker,
    FightBatThenMonsterMiddleTestTracker,
    FindStoneGargoylesTestTracker,
    GetToGreenDungeonRoomTestTracker,
    BeatStoneBossPurpleTestTracker,
    LoseToStoneBossPurpleTestTracker,
    FindLockedDoorTestTracker,
    CheckHousePointsTestTracker,
    HourglassTopThenBottomTestTracker,
    BottomRoomThenSealTestTracker,
    BetweenGargoylesThenSealTestTracker,
    LearnToCastSpellTestTracker,
    SelectCastSpellTestTracker,
    SelectCardAttackTestTracker,
    SelectUseItemTestTracker,
    SelectFleeTestTracker,
    SelectFolioBrutiTestTracker,
    RestoreAllMagicTestTracker,
    BroomDoomTestTracker,
    UseCardAttackTestTracker,
    FightSprinklerLeadTestTracker,
    FightGreenRatLeadTestTracker,
    FightGnomeTopLeftTestTracker,
    FightGreyHoseTopLeftTestTracker,
    ReachDiagonAlleyTestTracker,
    TalkToFredGeorgeFirstTimeTestTracker,
    TalkToFredGeorgeSecondTimeTestTracker,
    TalkToGreenStatueTestTracker,
    TalkToMomFirstTimeTestTracker,
    TalkToMomSecondTimeTestTracker,
    TalkToDadFirstTimeTestTracker,
    TalkToDadSecondTimeTestTracker,
    TalkToPercyTestTracker,
)

GAME_TO_GB_NAME = {
    "harry_potter_philosophers_stone": "HarryPotterPhilosophersStone.gbc",
    "harry_potter_chamber_of_secrets": "HarryPotterChamberOfSecrets.gbc",
}
""" Expected save name for each game. Save the file to <storage_dir_from_config_file>/<game_name>_rom_data/<gb_name>"""

STRONGEST_PARSERS: Dict[str, Type[StateParser]] = {
    "harry_potter_philosophers_stone": HarryPotterPhilosophersStoneParser,
    "harry_potter_chamber_of_secrets": HarryPotterChamberOfSecretsParser,
}
""" Mapping of game names to their corresponding strongest StateParser classes.
Unless you have a very good reason, you should always use the STRONGEST possible parser for a given game.
The parser itself does not affect performance, as for it to perform a read / screen comparison operation , it must be called upon by the state tracker.
This means there is never a reason to use a weaker parser.
"""


AVAILABLE_STATE_TRACKERS: Dict[str, Dict[str, Type[StateTracker]]] = {
    "harry_potter_philosophers_stone": {
        "default": HarryPotterOCRTracker,
        "ocr": HarryPotterOCRTracker,
        "receive_folio_magi_test": ReceiveFolioMagiTestTracker,
        "select_card_deck_test": SelectCardDeckTestTracker,
        "talk_hagrid_gringotts_test": TalkHagridGringottsTestTracker,
        "exit_gringotts_without_hagrid_test": ExitGringottsWithoutHagridTestTracker,
        "get_on_train_test": GetOnTrainTestTracker,
        "buy_chocolate_frogs_test": BuyChocolateFrogsTestTracker,
        "sell_one_chocolate_frog_test": SellOneChocolateFrogTestTracker,
        "lose_duel_test": LoseDuelTestTracker,
        "win_duel_test": WinDuelTestTracker,
        "gain_level_test": GainLevelTestTracker,
        "gain_spell_test": GainSpellTestTracker,
        "win_battle_test": WinBattleTestTracker,
        "beat_boss_rat_test": BeatBossRatTestTracker,
        "fail_rat_king_battle": FailRatKingBattleTestTracker,
        "defeat_rat_king_with_deflect_test": DefeatRatKingWithDeflectTestTracker,
        "find_hagrid_vault_test": FindHagridVaultTestTracker,
        "enter_malkins_test": EnterMalkinsTestTracker,
        "open_malkins_buy_menu_test": OpenMalkinsBuyMenuTestTracker,
        "select_robes_test": SelectRobesTestTracker,
        "confirm_robes_purchase_test": ConfirmRobesPurchaseTestTracker,
        "enter_flourish_blotts_test": EnterFlourishBlottsTestTracker,
        "buy_books_test": BuyBooksTestTracker,
        "enter_apothecary_test": EnterApothecaryTestTracker,
        "buy_potion_kit_test": BuyPotionKitTestTracker,
        "enter_cauldron_shop_test": EnterCauldronShopTestTracker,
        "buy_cauldron_test": BuyCauldronTestTracker,
        "enter_sugarplums_test": EnterSugarplumsTestTracker,
        "open_sugarplums_buy_menu_test": OpenSugarplumsBuyMenuTestTracker,
        "walk_train_3_times": WalkTrain3TimesTestTracker,
        "talk_to_hagrid_diagon_test": TalkToHagridDiagonTestTracker,
        "start_menu_test": StartMenuTestTracker,
        "eat_pumpkin_pasty_test": EatPumpkinPastyTestTracker,
        "equip_pointed_hat_plain_work_robe_test": EquipPointedHatPlainWorkRobeTestTracker,
        "remove_all_equipped_items_test": RemoveAllEquippedItemsTestTracker,
        "talk_to_hagrid_boat_test": TalkToHagridBoatTestTracker,
        "die_test": DieTestTracker,
        "fight_rat_then_monster_test": FightRatThenMonsterTestTracker,
        "fight_bat_then_monster_middle_test": FightBatThenMonsterMiddleTestTracker,
        "find_stone_gargoyles_test": FindStoneGargoylesTestTracker,
        "get_to_green_dungeon_room_test": GetToGreenDungeonRoomTestTracker,
        "beat_stone_boss_purple_test": BeatStoneBossPurpleTestTracker,
        "lose_to_stone_boss_purple_test": LoseToStoneBossPurpleTestTracker,
        "find_locked_door_test": FindLockedDoorTestTracker,
        "check_house_points_test": CheckHousePointsTestTracker,
        "hourglass_top_then_bottom_test": HourglassTopThenBottomTestTracker,
        "bottom_room_then_seal_test": BottomRoomThenSealTestTracker,
        "between_gargoyles_then_seal_test": BetweenGargoylesThenSealTestTracker,
    },
    "harry_potter_chamber_of_secrets": {
        "default": HarryPotterOCRTracker,
        "ocr": HarryPotterOCRTracker,
        "find_dobby_test": FindDobbyTestTracker,
        "select_card_deck_cos_test": SelectCardDeckCosTestTracker,
        "board_flying_car_test": BoardFlyingCarTestTracker,
        "enter_burrow_test": EnterBurrowTestTracker,
        "enter_battle_cos_test": EnterBattleCosTestTracker,
        "enter_percy_room_test": EnterPercyRoomTestTracker,
        "enter_ginny_room_test": EnterGinnyRoomTestTracker,
        "enter_parents_room_test": EnterParentsRoomTestTracker,
        "enter_fred_george_room_test": EnterFredGeorgeRoomTestTracker,
        "enter_rons_room_test": EnterRonsRoomTestTracker,
        "talk_to_ron_burrow_test": TalkToRonBurrowTestTracker,
        "enter_kitchen_burrow_test": EnterKitchenBurrowTestTracker,
        "enter_burrow_garden_test": EnterBurrowGardenTestTracker,
        "navigate_to_car_test": NavigateToCarTestTracker,
        "learn_to_cast_spell_test": LearnToCastSpellTestTracker,
        "select_cast_spell_test": SelectCastSpellTestTracker,
        "select_card_attack_test": SelectCardAttackTestTracker,
        "select_use_item_test": SelectUseItemTestTracker,
        "select_flee_test": SelectFleeTestTracker,
        "select_folio_bruti_test": SelectFolioBrutiTestTracker,
        "restore_all_magic_test": RestoreAllMagicTestTracker,
        "broom_doom_test": BroomDoomTestTracker,
        "use_card_attack_test": UseCardAttackTestTracker,
        "fight_sprinkler_lead_test": FightSprinklerLeadTestTracker,
        "fight_green_rat_lead_test": FightGreenRatLeadTestTracker,
        "fight_gnome_top_left_test": FightGnomeTopLeftTestTracker,
        "fight_grey_hose_top_left_test": FightGreyHoseTopLeftTestTracker,
        "reach_diagon_alley_test": ReachDiagonAlleyTestTracker,
        "talk_to_fred_george_first_time_test": TalkToFredGeorgeFirstTimeTestTracker,
        "talk_to_fred_george_second_time_test": TalkToFredGeorgeSecondTimeTestTracker,
        "talk_to_green_statue_test": TalkToGreenStatueTestTracker,
        "talk_to_mom_first_time_test": TalkToMomFirstTimeTestTracker,
        "talk_to_mom_second_time_test": TalkToMomSecondTimeTestTracker,
        "talk_to_dad_first_time_test": TalkToDadFirstTimeTestTracker,
        "talk_to_dad_second_time_test": TalkToDadSecondTimeTestTracker,
        "talk_to_percy_test": TalkToPercyTestTracker,
    },
}
""" Mapping of game names to their available StateTracker classes with string identifiers. """


AVAILABLE_EMULATORS: Dict[str, Dict[str, Type[Emulator]]] = {
    "harry_potter_philosophers_stone": {"default": Emulator},
    "harry_potter_chamber_of_secrets": {"default": Emulator},
}
""" Mapping of game names to their available Emulator classes with string identifiers. """
